services:
  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    network_mode: host
    healthcheck:
      test: [ "CMD", "mosquitto_pub", "-h", "localhost", "-t", "healthcheck", "-m", "ok" ]
      interval: 10s
      timeout: 10s
      retries: 5

  ardupilot-sitl:
    build:
      context: ./ardupilot-sitl
    container_name: ardupilot-sitl
    depends_on:
      mqtt:
        condition: service_healthy

    ports:
      - "14550:14550"
    network_mode: host

  node-red:
    image: nodered/node-red
    container_name: node-red
    ports:
      - "1880:1880"
    depends_on:
      - mqtt
    volumes:
      - ./node-red/data:/data
    network_mode: host
