services:
  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - drone-network

  ardupilot-sitl:
    build:
      context: ./ardupilot-sitl
    container_name: ardupilot-sitl
    network_mode: host
    ports:
      - "14550:14550"

  node-red:
    image: nodered/node-red
    container_name: node-red
    ports:
      - "1880:1880"
    depends_on:
      - mqtt
    volumes:
      - ./node-red/data:/data
    networks:
      - drone-network

networks:
  drone-network:
    driver: bridge
